/** Notes export — Markdown (for copy) and a typeset PDF via latex-compiler. */

import { integration } from 'deepspace'
import type { GistContent, VideoMeta } from './gist-pipeline'
import { buildLatexDocument } from './latex'

/** Plain-text / Markdown rendering of the notes, used by the "Copy notes" button. */
export function buildMarkdownNotes(meta: VideoMeta, gist: GistContent): string {
  const lines: string[] = []
  lines.push(`# ${meta.title || 'YouTube video'}`)
  const sub = [meta.channel, meta.duration].filter(Boolean).join(' · ')
  if (sub) lines.push(`_${sub}_`)
  lines.push(meta.url)
  lines.push('')

  if (gist.tldr) {
    lines.push('## TL;DR', gist.tldr, '')
  }

  if (gist.deepDive.length) {
    lines.push('## The long read')
    for (const para of gist.deepDive) lines.push(para, '')
  }

  if (gist.chapters.length) {
    lines.push('## Chapters')
    for (const c of gist.chapters) {
      lines.push(`- **[${c.startTimestamp}] ${c.title}** — ${c.summary}`)
    }
    lines.push('')
  }

  if (gist.steps.length) {
    lines.push('## Steps')
    gist.steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`))
    lines.push('')
  }

  if (gist.keyQuotes.length) {
    lines.push('## Key quotes')
    for (const q of gist.keyQuotes) lines.push(`> "${q}"`)
    lines.push('')
  }

  lines.push('---', `Generated by Gist`)
  return lines.join('\n')
}

function base64ToBlob(b64: string, type: string): Blob {
  const binary = atob(b64)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return new Blob([bytes], { type })
}

function safeFilename(title: string): string {
  const base = (title || 'gist').replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase()
  return `${base || 'gist'}.pdf`
}

/**
 * Compile the notes to a PDF via the latex-compiler integration and trigger a
 * download. Throws on failure so the caller can fall back to print-to-PDF.
 */
export async function downloadGistPdf(meta: VideoMeta, gist: GistContent): Promise<void> {
  const document = buildLatexDocument(meta, gist)
  const res = await integration.post('latex-compiler/compile', {
    compiler: 'pdflatex',
    document,
  })

  if (!res || res.success !== true) {
    throw new Error(
      (res && 'error' in res && typeof res.error === 'string' && res.error) ||
        'PDF compilation failed',
    )
  }

  const data = res.data as { compiled?: boolean; pdfBase64?: string }
  if (!data.compiled || !data.pdfBase64) {
    throw new Error('PDF compilation failed')
  }

  const blob = base64ToBlob(data.pdfBase64, 'application/pdf')
  const url = URL.createObjectURL(blob)
  const a = window.document.createElement('a')
  a.href = url
  a.download = safeFilename(meta.title)
  window.document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 4000)
}
