/**
 * Build a polished LaTeX document from a gist, for the latex-compiler
 * integration. Everything user/model-derived is escaped/sanitized so the
 * compile can't be broken by stray TeX metacharacters or exotic unicode.
 */

import type { GistContent, VideoMeta } from './gist-pipeline'

/** Convert common unicode punctuation to ASCII and drop anything pdflatex can't set. */
function sanitize(input: string): string {
  if (!input) return ''
  return input
    .replace(/[‘’‚′]/g, "'")
    .replace(/[“”„″]/g, '"')
    .replace(/[–—]/g, '--')
    .replace(/…/g, '...')
    .replace(/[   ​]/g, ' ')
    .replace(/[•▪●]/g, '-')
    // Keep newline/tab, printable ASCII, and Latin-1/Extended; drop emoji, CJK,
    // and other symbols the default pdflatex engine can't typeset.
    .replace(/[^\n\t -~¡-ɏ]/g, '')
}

/** Escape TeX special characters in already-sanitized text. */
function tex(input: string): string {
  const s = sanitize(input)
  return s
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([&%$#_{}])/g, '\\$1')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}')
}

function itemize(items: string[], ordered = false): string {
  if (items.length === 0) return ''
  const env = ordered ? 'enumerate' : 'itemize'
  const body = items.map((it) => `  \\item ${tex(it)}`).join('\n')
  return `\\begin{${env}}[leftmargin=1.4em, itemsep=0.35em]\n${body}\n\\end{${env}}`
}

export function buildLatexDocument(meta: VideoMeta, gist: GistContent): string {
  const title = tex(meta.title || 'YouTube video')
  const channel = tex(meta.channel || '')
  const duration = tex(meta.duration || '')
  const metaLine = [channel, duration].filter(Boolean).join('  \\textbullet{}  ')

  const sections: string[] = []

  if (gist.tldr) {
    sections.push(`\\section*{TL;DR}\n${tex(gist.tldr)}`)
  }

  if (gist.chapters.length > 0) {
    const rows = gist.chapters
      .map(
        (c) =>
          `\\item[\\textbf{${tex(c.startTimestamp)}}] \\textbf{${tex(c.title)}}\\\\\n${tex(c.summary)}`,
      )
      .join('\n\\smallskip\n')
    sections.push(
      `\\section*{Chapters}\n\\begin{description}[leftmargin=!, labelwidth=3.2em, itemsep=0.5em]\n${rows}\n\\end{description}`,
    )
  }

  if (gist.steps.length > 0) {
    sections.push(`\\section*{Steps}\n${itemize(gist.steps, true)}`)
  }

  if (gist.keyQuotes.length > 0) {
    const quotes = gist.keyQuotes
      .map((q) => `\\begin{quote}\\itshape \`\`${tex(q)}''\\end{quote}`)
      .join('\n')
    sections.push(`\\section*{Key quotes}\n${quotes}`)
  }

  return `\\documentclass[11pt]{article}
\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\usepackage[margin=1in]{geometry}
\\usepackage{enumitem}
\\usepackage{parskip}
\\usepackage{xcolor}
\\usepackage[hidelinks]{hyperref}
\\definecolor{accent}{HTML}{2563EB}
\\definecolor{muted}{HTML}{6B7280}
\\setlist{nosep}
\\renewcommand{\\familydefault}{\\sfdefault}

\\begin{document}
\\thispagestyle{empty}

{\\color{muted}\\small GIST \\textbullet{} VIDEO NOTES}\\\\[0.3em]
{\\LARGE\\bfseries ${title}\\par}
${metaLine ? `\\vspace{0.3em}{\\color{muted}${metaLine}\\par}` : ''}
\\vspace{0.4em}
{\\color{accent}\\hrule height 2pt}
\\vspace{1.2em}

${sections.join('\n\n\\vspace{0.6em}\n\n')}

\\vfill
{\\color{muted}\\small Generated by Gist \\textbullet{} \\href{${meta.url}}{${tex(meta.url)}}}
\\end{document}`
}
